"""add_full_name_to_user

Revision ID: 384988171dc0
Revises: 001_initial
Create Date: 2026-03-06 23:36:11.044233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384988171dc0'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.drop_constraint(op.f('jobs_user_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_style_cache_id'), 'style_cache', ['id'], unique=False)
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_style_cache_id'), table_name='style_cache')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_user_id_fkey'), 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.alter_column('jobs', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
